name: llm_dev
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.24.0,<2.0.0  # Pin to <2.0 for compatibility with ML ecosystem
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - jupyter
  - jupyterlab>=4.0.0
  - ipywidgets>=8.0.0
  - ipykernel>=6.25.0
  - nbformat>=5.9.0
  - nodejs>=18.0.0  # Required for JupyterLab extensions
  - pytorch>=2.0.0
  - pytorch-cuda=11.8  # For CUDA support, adjust version as needed
  - pip:
    - torch>=2.0.0,<2.2.0
    - transformers>=4.30.0,<5.0.0
    - huggingface-hub>=0.16.0,<1.0.0
    - datasets>=2.12.0,<3.0.0
    - tokenizers>=0.13.0,<1.0.0
    - accelerate>=0.20.0,<1.0.0
    - safetensors>=0.3.0
    - regex>=2023.6.3
    - tqdm>=4.65.0
    - wandb>=0.15.0
    - tensorboard>=2.13.0
    - langchain>=0.0.200
    - chromadb>=0.4.0
    - faiss-cpu>=1.7.4
    - sentence-transformers>=2.2.0
    - fastapi>=0.100.0
    - uvicorn>=0.22.0
    - requests>=2.31.0
    - pyyaml>=6.0
    - click>=8.1.0
    - python-dotenv>=1.0.0
    - typing-extensions>=4.5.0
    - packaging>=23.0
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - black>=23.0.0
    - flake8>=6.0.0
    - isort>=5.12.0